# Generated by Django 3.2.13 on 2022-09-22 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Unico')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('password', models.CharField(db_column='senha', max_length=100, verbose_name='Senha')),
                ('is_superuser', models.BooleanField(db_column='is_admin', default=False, help_text='E administrador do sistema!', verbose_name='Administrador')),
                ('alterar_senha_proximo_login', models.BooleanField(default=True, help_text='Precisa alterar a senha no proximo login', verbose_name='Alterar senha proximo login')),
                ('is_staff', models.BooleanField(default=False)),
                ('reset_senha', models.CharField(max_length=36, null=True, verbose_name='Cod reset Senha')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
